### ISSUE TITLE
[Bug]  Can't run npm install nor yarn install

### ISSUE THREAD

**Issue by gmatosferreira** [creativetimofficial/argon-dashboard-material-ui#4]
### Version
1.0.0 (on main branch)
### Reproduction link
https://github.com/creativetimofficial/argon-dashboard-material-ui/tree/main
### Operating System
Manjaro Linux / Ubuntu
### Device
Asus Vivobook / Dell
### Browser & Version
Firefox 92.0.1
### Steps to reproduce
I have done the following steps:
1. Cloned the repo;
2. npm install

In both the installation throws an error that I can't identify. Below I share the logs:
- npm i: https://www.codepile.net/pile/eLOKlKLg
- npm i --force: https://www.codepile.net/pile/dN0Aepl7

I have also tried to install with yarn, but it also throws error.
### What is expected?
Install without errors.
### What is actually happening?
Installing process is aborted because an error is thrown.

---

**Comment by rukaury** [comment]
I had the same issue. The issue for me at this moment was with two packages react-datetime and node-sass. SO I changed the version of package.json to use the latest version and no more errors. The react-datetime had some dependency issue with react version and the node-sass had an issue with the version of node that I was using (v16).

**Comment by sajadevo** [comment]
**Hi @pubnubcraig**

Thanks for using our product, I've updated the product and now it has a new and fresh design + a new base structure that contains more reusable and scalable code.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
