### ISSUE TITLE
[Feature Request] Material UI V5.x

### ISSUE THREAD

**Issue by o0Djeen0o** [creativetimofficial/argon-dashboard-material-ui#5]
### What is your enhancement?
Hi, 

Material UI v5.x is now available https://mui.com.
For new projects, it seems strange to remain on old v4 version with the huge modifications implied afterwards for the transition between both versions. I've seen that a 2.0 branch has been created with an alpha integration for Material UI 5, will it be possible to have a idea of delivery for such update to be productively available?
Thanks for your help and best regards.

**Comment by sajadevo** [comment]
**Hi @pubnubcraig**

Thanks for using our product, I've updated the product and now it has a new and fresh design + a new base structure that contains more reusable and scalable code.
Now it also uses the MUI v5 dependencies and packages.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
