### ISSUE TITLE
[Bug] Sidenav is transparent on mobile ans small screens

### ISSUE THREAD

**Issue by 40uf411** [creativetimofficial/argon-dashboard-material-ui#9]
### Version
3
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-material-ui/#/dashboard
### Operating System
Linux
### Device
PC
### Browser & Version
Latest Opera
### Steps to reproduce
1. Resize the screen to mobile size.
2. open the sidenav.
### What is expected?
The sidenav should have a white or dark background.
### What is actually happening?
The background is transparent which does not allow people to clearly see the sidenav items

---

**Comment by 40uf411** [comment]
![image](https://user-images.githubusercontent.com/29804103/194360167-7d56a53f-c1de-45b8-9faf-9a2439488876.png)

**Comment by 40uf411** [comment]
This issue exists in the pro version as well.

**Comment by Manasseh-Ankrah** [comment]
I solved this issue by going to SideNavRoot.js file and changing the MuiDrawer-paper backgroundColor to white.

  return {
    "& .MuiDrawer-paper": {
      boxShadow: xxl,
      border: "none",
      backgroundColor: "white",

      ...(miniSidenav ? drawerCloseStyles() : drawerOpenStyles()),
    },
  };

**Comment by Manasseh-Ankrah** [comment]
I solved this issue by going to SidenavRoot.js file and changing the MuiDrawer-paper backgroundColor to white.

return {
"& .MuiDrawer-paper": {
boxShadow: xxl,
border: "none",
backgroundColor: "white",

  ...(miniSidenav ? drawerCloseStyles() : drawerOpenStyles()),
},
};

**Comment by mark-w-325** [comment]
To keep consistent with the code being used, you should set the backgroundColor to the variable bgColor. This will allow you to use the dark them as well as light them. Below is the code I used:

`  return {
    "& .MuiDrawer-paper": {
      boxShadow: xxl,
      border: "none",
      backgroundColor: bgColor,

      ...(miniSidenav ? drawerCloseStyles() : drawerOpenStyles()),
    },
  };
});`

**Comment by aaronm-git** [comment]
> To keep consistent with the code being used, you should set the backgroundColor to the variable bgColor. This will allow you to use the dark them as well as light them. Below is the code I used:
> 
> ```
> return {
>     "& .MuiDrawer-paper": {
>       boxShadow: xxl,
>       border: "none",
>       backgroundColor: bgColor,
> 
>       ...(miniSidenav ? drawerCloseStyles() : drawerOpenStyles()),
>     },
>   };
> });
> ```

can we get this solution merged?

**Comment by sajadevo** [comment]
This issue is fixed on v3.0.1.
